; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Pattern Matcher"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Sideralsoft"
#define MyAppURL "https://www.sideralsoft.com/"
#define MyAppExeName "pattern-matcher.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".pmf"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D27DD101-EC21-4F22-9029-30D9310E65AC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableDirPage=yes
UninstallDisplayIcon={app}\{#MyAppExeName}
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\jhoah\Desktop\Accesos
OutputBaseFilename=pattern-matcher-setup
SolidCompression=yes
WizardStyle=modern
; SignTool=path\to\signtool.exe sign /f "path\to\certificate.pfx" /p "password" /t "http://timestamp.server.url" $f

[Languages]
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "D:\Universidad\Tesis\Instalaciones\pattern-matcher\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Universidad\Tesis\Instalaciones\pattern-matcher\config.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Universidad\Tesis\Instalaciones\pattern-matcher\launch4j.log"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Universidad\Tesis\Instalaciones\pattern-matcher\README.TXT"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Universidad\Tesis\Instalaciones\pattern-matcher\lib\*"; DestDir: "{app}\lib"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
; Instala el certificado en el almacén raíz para todos los usuarios
; Filename: "certutil"; Parameters: "-addstore root ""{tmp}\mycert.cer"""; StatusMsg: "Installing certificate..."


; [UninstallRun]
; Elimina el certificado del almacén raíz
; Filename: "certutil"; Parameters: "-delstore root ""My Certificate Friendly Name"""; StatusMsg: "Removing certificate..."


